#! /bin/sh

URL="http://localhost:9393"

create_stream() {
  curl -v -H "Accept: application/json" -d name=$1 --data-urlencode "definition=$2" "$URL/streams"
}

undeploy_stream() {
  curl -v -H "Accept: application/json" -X PUT -d deploy=false "$URL/streams/$1"
}

create_stream mem "http | log"
create_stream cpu "http --port=9001 | log"
create_stream memgauge "tap:mem > richgauge"
create_stream cpugauge "tap:cpu > richgauge"

