#! /bin/sh

URL="http://localhost:9393"

create_stream() {
  curl -v -H "Accept: application/json" -d name=$1 --data-urlencode "definition=$2" "$URL/streams"
}

undeploy_stream() {
  curl -v -H "Accept: application/json" -X PUT -d deploy=false "$URL/streams/$1"
}

deploy_stream() {
  curl -v -H "Accept: application/json" -X PUT -d deploy=true "$URL/streams/$1"
}

create_stream "tweets" "twitterstream | file"
sleep 2
undeploy_stream "tweets"

create_stream "tweetcount" "tap:tweets > aggregatecounter"

create_stream "tweetlang" "tap:tweets > field-value-counter --fieldName=lang"

create_stream "tagcount" "tap:tweets > field-value-counter --fieldName=entities.hashtags.text --counterName=hashtags"


