#! /bin/sh

URL="http://localhost:8080"

curl -v -H "Accept: application/json" -d name=tweets -d definition=twitterstream+%7C+file "$URL/streams"

curl -v -H "Accept: application/json" -X PUT -d deploy=false "$URL/streams/tweets"

curl -v -H "Accept: application/json" -d name=tweetcount -d definition="tap+tweets+%7C+aggregatecounter" "$URL/taps"

curl -v -H "Accept: application/json" -d name=tagcount -d definition="tap+tweets+%7C+field-value-counter+--fieldName=entities.hashtags.text+--counterName=hashtags" "$URL/taps"

curl -v -H "Accept: application/json" -d name=tweetlang -d definition="tap+tweets+%7C+field-value-counter+--fieldName=lang" "$URL/taps"

curl -v -H "Accept: application/json" -X PUT -d deploy=true "$URL/streams/tweets"
